"""
Sprint 1 - S1-02: Clean the dashboard data.

Reads every file in raw_data/, fixes country labels, booleans, currency
values, dates, nulls, and duplicates, and writes one matching file per
source into clean_data/. Also writes a data-quality report to
docs/data_quality_report.md so the numbers behind S1-03 are reproducible,
not just eyeballed once.

Run from the project root:
    python src/clean_data.py
"""

import pandas as pd
from pathlib import Path

RAW_DIR = Path(__file__).resolve().parent.parent / "raw_data"
CLEAN_DIR = Path(__file__).resolve().parent.parent / "clean_data"
DOCS_DIR = Path(__file__).resolve().parent.parent / "docs"
CLEAN_DIR.mkdir(exist_ok=True)

report_lines = ["# Data Quality Report\n", "Generated by `src/clean_data.py`. Numbers below are measured, not estimated.\n"]


def log(line=""):
    print(line)
    report_lines.append(line)


COUNTRY_MAP = {
    "usa": "US", "u.s.": "US", "usa".upper(): "US", "us": "US",
    "uk": "UK", "de": "DE",
}


def normalize_country(series):
    return series.str.strip().str.lower().map(
        lambda v: COUNTRY_MAP.get(v, v.upper())
    )


def normalize_bool(series):
    mapping = {"1": True, "0": False, "true": True, "false": False,
               "yes": True, "no": False}
    return series.astype(str).str.strip().str.lower().map(mapping)


def strip_currency(series):
    return (
        series.astype(str)
        .str.replace(r"[\$,]", "", regex=True)
        .astype(float)
    )


# ---------------------------------------------------------------- customers
log("\n## customers.csv")
customers = pd.read_csv(RAW_DIR / "customers.csv")
before = len(customers)

customers["country_code"] = normalize_country(customers["country_code"])
customers["credit_limit"] = strip_currency(customers["credit_limit"])

# age: "unknown" -> null, rest to numeric
age_numeric = pd.to_numeric(customers["age"], errors="coerce")
n_unknown_age = age_numeric.isna().sum()
customers["age"] = age_numeric

customers["signup_date"] = pd.to_datetime(customers["signup_date"], errors="coerce")

dupes = customers.duplicated().sum()
customers = customers.drop_duplicates()

# drop noise columns, not useful for dashboard or model
noise_cols = [c for c in customers.columns if c.startswith("noise_")]
customers = customers.drop(columns=noise_cols)

log(f"- rows before: {before}, after: {len(customers)}")
log(f"- duplicate rows removed: {dupes}")
log(f"- age values that were literally 'unknown', set to null: {n_unknown_age}")
log(f"- email_open_rate nulls left as-is (real missing data): {customers['email_open_rate'].isna().sum()}")
log(f"- country_code values after cleaning: {sorted(customers['country_code'].unique())}")
log(f"- dropped noise columns: {noise_cols}")

customers.to_csv(CLEAN_DIR / "clean_customers.csv", index=False)

# ----------------------------------------------------------------- sessions
log("\n## sessions.csv")
sessions = pd.read_csv(RAW_DIR / "sessions.csv")
before = len(sessions)

sessions["bounce_flag"] = normalize_bool(sessions["bounce_flag"])
sessions["traffic_source"] = sessions["traffic_source"].str.strip().str.lower()
sessions["device_type"] = sessions["device_type"].str.strip().str.lower()
sessions["session_timestamp"] = pd.to_datetime(sessions["session_timestamp"], errors="coerce")

dupes = sessions.duplicated().sum()
sessions = sessions.drop_duplicates()

# key coverage check, not assumed
valid_customers = set(customers["customer_id"])
valid_geo = set(pd.read_csv(RAW_DIR / "geo_data.csv")["geo_ip_region"])
valid_campaigns = set(pd.read_csv(RAW_DIR / "marketing_campaigns.csv")["campaign_id"])
orphan_customer = (~sessions["customer_id"].isin(valid_customers)).sum()
orphan_geo = (~sessions["geo_ip_region"].isin(valid_geo)).sum()
orphan_campaign = (~sessions["campaign_id"].isin(valid_campaigns)).sum()

log(f"- rows before: {before}, after: {len(sessions)}")
log(f"- duplicate rows removed: {dupes}")
log(f"- pages_viewed nulls left as-is (real missing data): {sessions['pages_viewed'].isna().sum()}")
log(f"- orphan customer_id (not in customers): {orphan_customer}")
log(f"- orphan geo_ip_region (not in geo_data): {orphan_geo}")
log(f"- orphan campaign_id (not in marketing_campaigns): {orphan_campaign}")
log(f"- bounce_flag values after cleaning: {sorted(sessions['bounce_flag'].astype(str).unique())}")
log(f"- traffic_source values after cleaning: {sorted(sessions['traffic_source'].unique())}")
log(f"- device_type values after cleaning: {sorted(sessions['device_type'].unique())}")

sessions.to_csv(CLEAN_DIR / "clean_sessions.csv", index=False)

# ------------------------------------------------------------- transactions
log("\n## transactions.csv")
transactions = pd.read_csv(RAW_DIR / "transactions.csv")
before = len(transactions)

transactions["order_value"] = strip_currency(transactions["order_value"])
transactions["discount_applied"] = normalize_bool(transactions["discount_applied"])
transactions["transaction_timestamp"] = pd.to_datetime(transactions["transaction_timestamp"], errors="coerce")

dupes = transactions.duplicated().sum()
transactions = transactions.drop_duplicates()

noise_cols = [c for c in transactions.columns if c.startswith("noise_")]
transactions = transactions.drop(columns=noise_cols)

orphan_customer = (~transactions["customer_id"].isin(valid_customers)).sum()

log(f"- rows before: {before}, after: {len(transactions)}")
log(f"- duplicate rows removed: {dupes}")
log(f"- orphan customer_id (not in customers): {orphan_customer}")
log(f"- order_value range after cleaning: {transactions['order_value'].min():.2f} to {transactions['order_value'].max():.2f}")
log(f"- discount_applied values after cleaning: {sorted(transactions['discount_applied'].astype(str).unique())}")
log(f"- dropped noise columns: {noise_cols}")

transactions.to_csv(CLEAN_DIR / "clean_transactions.csv", index=False)

# ------------------------------------------------------------------ geo_data
log("\n## geo_data.csv")
geo = pd.read_csv(RAW_DIR / "geo_data.csv")
dupes = geo.duplicated().sum()
geo = geo.drop_duplicates()
log(f"- rows: {len(geo)}, duplicates removed: {dupes}, nulls: {geo.isnull().sum().sum()}")
geo.to_csv(CLEAN_DIR / "clean_geo_data.csv", index=False)

# --------------------------------------------------------- marketing_campaigns
log("\n## marketing_campaigns.csv")
camp = pd.read_csv(RAW_DIR / "marketing_campaigns.csv")
dupes = camp.duplicated().sum()
camp = camp.drop_duplicates()
camp["start_date"] = pd.to_datetime(camp["start_date"], errors="coerce")
camp["end_date"] = pd.to_datetime(camp["end_date"], errors="coerce")
bad_dates = camp["start_date"].isna().sum() + camp["end_date"].isna().sum()
log(f"- rows: {len(camp)}, duplicates removed: {dupes}, invalid dates: {bad_dates}")
camp.to_csv(CLEAN_DIR / "clean_marketing_campaigns.csv", index=False)

# -------------------------------------------------------------- write report
DOCS_DIR.mkdir(exist_ok=True)
with open(DOCS_DIR / "data_quality_report.md", "w") as f:
    f.write("\n".join(report_lines) + "\n")

print("\nDone. Clean files are in clean_data/, report is in docs/data_quality_report.md")
